-- ============================================================
-- DB2 Objects for collections domain — variant 42
-- Pacific National Bank
-- ============================================================

CREATE VIEW PNB.V_COLLECTIONS_042 AS
  SELECT
    COL_000,
    COL_001,
    COL_002,
    COL_003,
    COL_004,
    COL_005,
    COL_006,
    COL_007,
    COL_008,
    COL_009,
    COL_010,
    COL_011,
    COL_012,
    COL_013,
    COL_014,
    COL_015,
    COL_016,
    COL_017,
    COL_018,
    COL_019,
    COL_020,
    COL_021,
    COL_022,
    COL_023,
    COL_024
  FROM PNB.COLLECTIONS_MASTER
  WHERE STATUS = 'A';

CREATE TRIGGER PNB.TRG_COLLECTIONS_042_UPDATE
  AFTER UPDATE ON PNB.COLLECTIONS_MASTER
  REFERENCING NEW AS N OLD AS O
  FOR EACH ROW
  MODE DB2SQL
  BEGIN ATOMIC
    INSERT INTO PNB.COLLECTIONS_AUDIT (
      AUDIT_ID, TABLE_NAME, OPERATION, OLD_VALUE, NEW_VALUE,
      CHANGED_BY, CHANGED_AT
    ) VALUES (
      DEFAULT, 'COLLECTIONS_MASTER', 'UPDATE',
      CAST(O.COL_000 AS VARCHAR(200)),
      CAST(N.COL_000 AS VARCHAR(200)),
      CURRENT USER, CURRENT TIMESTAMP
    );
  END;

CREATE OR REPLACE PROCEDURE PNB.SP_COLLECTIONS_042 (
  IN  p_key       VARCHAR(32),
  IN  p_operation VARCHAR(10),
  OUT p_status    INTEGER,
  OUT p_message   VARCHAR(200)
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
  DECLARE v_field_00 VARCHAR(100);
  DECLARE v_field_01 VARCHAR(100);
  DECLARE v_field_02 VARCHAR(100);
  DECLARE v_field_03 VARCHAR(100);
  DECLARE v_field_04 VARCHAR(100);
  DECLARE v_field_05 VARCHAR(100);
  DECLARE v_field_06 VARCHAR(100);
  DECLARE v_field_07 VARCHAR(100);
  DECLARE v_count INTEGER;
  DECLARE v_amount DECIMAL(15,2);
  DECLARE SQLSTATE CHAR(5);
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET p_status = -1;
    SET p_message = 'SQL error: ' || SQLSTATE;
  END;

  IF p_operation = 'GET' THEN
    SELECT COL_000, COL_001 INTO v_field_00, v_field_01
      FROM PNB.COLLECTIONS_MASTER
      WHERE COL_000 = p_key;
    SET p_status = 0;
    SET p_message = 'Record found';
  ELSEIF p_operation = 'COUNT' THEN
    SELECT COUNT(*) INTO v_count
      FROM PNB.COLLECTIONS_MASTER
      WHERE STATUS = 'A';
    SET p_status = v_count;
    SET p_message = 'Count: ' || CHAR(v_count);
  ELSE
    SET p_status = -2;
    SET p_message = 'Unknown operation: ' || p_operation;
  END IF;
END;

CREATE INDEX PNB.IX_COLLECTIONS_042_00
  ON PNB.COLLECTIONS_MASTER (COL_000 ASC);

CREATE INDEX PNB.IX_COLLECTIONS_042_01
  ON PNB.COLLECTIONS_MASTER (COL_001 ASC);

CREATE INDEX PNB.IX_COLLECTIONS_042_02
  ON PNB.COLLECTIONS_MASTER (COL_002 ASC);

CREATE INDEX PNB.IX_COLLECTIONS_042_03
  ON PNB.COLLECTIONS_MASTER (COL_003 ASC);

