-- ============================================================
-- DB2 Objects for mortgage domain — variant 27
-- Pacific National Bank
-- ============================================================

CREATE VIEW ACB.V_MORTGAGE_027 AS
  SELECT
    COL_000,
    COL_001,
    COL_002,
    COL_003,
    COL_004,
    COL_005,
    COL_006,
    COL_007,
    COL_008,
    COL_009,
    COL_010,
  FROM ACB.MORTGAGE_MASTER
  WHERE STATUS = 'A';

CREATE TRIGGER ACB.TRG_MORTGAGE_027_UPDATE
  AFTER UPDATE ON ACB.MORTGAGE_MASTER
  REFERENCING NEW AS N OLD AS O
  FOR EACH ROW
  MODE DB2SQL
  BEGIN ATOMIC
    INSERT INTO ACB.MORTGAGE_AUDIT (
      AUDIT_ID, TABLE_NAME, OPERATION, OLD_VALUE, NEW_VALUE,
      CHANGED_BY, CHANGED_AT
    ) VALUES (
      DEFAULT, 'MORTGAGE_MASTER', 'UPDATE',
      CAST(O.COL_000 AS VARCHAR(200)),
      CAST(N.COL_000 AS VARCHAR(200)),
      CURRENT USER, CURRENT TIMESTAMP
    );
  END;

CREATE OR REPLACE PROCEDURE ACB.SP_MORTGAGE_027 (
  IN  p_key       VARCHAR(32),
  IN  p_operation VARCHAR(10),
  OUT p_status    INTEGER,
  OUT p_message   VARCHAR(200)
)
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN
  DECLARE v_field_00 VARCHAR(100);
  DECLARE v_field_01 VARCHAR(100);
  DECLARE v_field_02 VARCHAR(100);
  DECLARE v_field_03 VARCHAR(100);
  DECLARE v_field_04 VARCHAR(100);
  DECLARE v_field_05 VARCHAR(100);
  DECLARE v_field_06 VARCHAR(100);
  DECLARE v_field_07 VARCHAR(100);
  DECLARE v_count INTEGER;
  DECLARE v_amount DECIMAL(15,2);
  DECLARE SQLSTATE CHAR(5);
  DECLARE EXIT HANDLER FOR SQLEXCEPTION
  BEGIN
    SET p_status = -1;
    SET p_message = 'SQL error: ' || SQLSTATE;
  END;

  IF p_operation = 'GET' THEN
    SELECT COL_000, COL_001 INTO v_field_00, v_field_01
      FROM ACB.MORTGAGE_MASTER
      WHERE COL_000 = p_key;
    SET p_status = 0;
    SET p_message = 'Record found';
  ELSEIF p_operation = 'COUNT' THEN
    SELECT COUNT(*) INTO v_count
      FROM ACB.MORTGAGE_MASTER
      WHERE STATUS = 'A';
    SET p_status = v_count;
    SET p_message = 'Count: ' || CHAR(v_count);
  ELSE
    SET p_status = -2;
    SET p_message = 'Unknown operation: ' || p_operation;
  END IF;
END;

CREATE INDEX ACB.IX_MORTGAGE_027_00
  ON ACB.MORTGAGE_MASTER (COL_000 ASC);

CREATE INDEX ACB.IX_MORTGAGE_027_01
  ON ACB.MORTGAGE_MASTER (COL_001 ASC);

CREATE INDEX ACB.IX_MORTGAGE_027_02
  ON ACB.MORTGAGE_MASTER (COL_002 ASC);

CREATE INDEX ACB.IX_MORTGAGE_027_03
  ON ACB.MORTGAGE_MASTER (COL_003 ASC);

CREATE INDEX ACB.IX_MORTGAGE_027_04
  ON ACB.MORTGAGE_MASTER (COL_004 ASC);

