-- IMS segment metadata synchronized with ims/dbdgen and ims/psbgen artifacts
CREATE TABLE IMS_SEGMENT_DEFINITION (
    DBD_NAME         VARCHAR(8)   NOT NULL,
    SEGMENT_NAME     VARCHAR(8)   NOT NULL,
    PARENT_SEGMENT   VARCHAR(8),
    KEY_FIELD        VARCHAR(64)  NOT NULL,
    KEY_LENGTH       INTEGER      NOT NULL,
    MAX_OCCURS       INTEGER      NOT NULL DEFAULT 1,
    SEGMENT_BYTES    INTEGER      NOT NULL,
    LAST_REVIEWED_BY VARCHAR(64)  NOT NULL,
    LAST_REVIEWED_TS TIMESTAMP    NOT NULL,
    PRIMARY KEY (DBD_NAME, SEGMENT_NAME)
);

INSERT INTO IMS_SEGMENT_DEFINITION
(DBD_NAME, SEGMENT_NAME, PARENT_SEGMENT, KEY_FIELD, KEY_LENGTH, MAX_OCCURS, SEGMENT_BYTES, LAST_REVIEWED_BY, LAST_REVIEWED_TS)
VALUES
('CUSTDB01', 'CUSTROOT', NULL, 'CUSTOMER_NUMBER', 12, 1, 256, 'IMS-ARCH', CURRENT TIMESTAMP),
('CUSTDB01', 'ACCTSEG', 'CUSTROOT', 'ACCOUNT_NUMBER', 14, 999, 320, 'IMS-ARCH', CURRENT TIMESTAMP),
('CUSTDB01', 'TXNSEG', 'ACCTSEG', 'POSTING_SEQUENCE', 10, 5000, 420, 'IMS-ARCH', CURRENT TIMESTAMP),
('CUSTDB01', 'KYCSEG', 'CUSTROOT', 'KYC_EVENT_ID', 16, 200, 280, 'IMS-ARCH', CURRENT TIMESTAMP);
